# Generated by Django 3.1.6 on 2021-02-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210211_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Additional_info',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_img1',
            field=models.ImageField(default='Default Value', upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_img2',
            field=models.ImageField(default='Default Value', upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_img3',
            field=models.ImageField(default='Default Value', upload_to='images'),
        ),
    ]
